import { FormEvent, useEffect, useRef, useState } from 'react'
import { API } from './api'
import RichNotesPage from './NotesPage'
import KnowledgePage from './KnowledgePage'
import DocumentsPage from './DocumentsPage'
import PublicationsPage from './PublicationsPage'
import FinancePage from './FinancePage'
import AIAssistantPage from './AIAssistantPage'
import ProjectsPage from './ProjectsPage'
import HabitsPage from './HabitsPage'
import AnalyticsPage from './AnalyticsPage'
import SettingsPage from './SettingsPage'
import AuthPage from './AuthPage'
import GitHubSettings from './GitHubSettings'
import GitHubMirror from './GitHubMirror'
import {
  Bold, BookOpen, Bookmark, Bot, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, FileText,
  FolderKanban, Grid2X2, HeartPulse, Library, Menu, MoreHorizontal, Plus,
  List, PanelLeft, Quote, Save, Search, Settings, Sparkles, Trash2, Type, TrendingUp, WalletCards, X
} from 'lucide-react'

const nav = [
  ['Dashboard', Grid2X2], ['Tasks', CheckCircle2], ['Calendar', CalendarDays], ['Notes', FileText],
  ['Knowledge Base', Library], ['Documents', FolderKanban], ['Publications', BookOpen], ['Finance', WalletCards],
  ['Habits', HeartPulse], ['Bookmarks', Bookmark], ['Media Library', Library], ['AI Assistant', Bot],
  ['Projects', FolderKanban], ['Analytics', TrendingUp]
] as const

const tasks = [
  { title: 'Outline Personal OS data model', project: 'Personal OS', due: 'Today', done: false },
  { title: 'Review weekly priorities', project: 'Life admin', due: 'Today', done: false },
  { title: 'Organize design references', project: 'Creative', due: 'Tomorrow', done: false },
]

type PersonalTask = { id: number; title: string; project: string | null; priority: 'low' | 'medium' | 'high'; due_date: string | null; completed: boolean }
type CalendarEvent = { id: number; title: string; event_date: string; start_time: string | null; color: 'forest' | 'purple' | 'orange' | 'blue' }
type Note = { id: number; title: string; content: string; parent_id: number | null; icon: string; updated_at: string }

function App() {
  const [authToken, setAuthToken] = useState(() => localStorage.getItem('personal-os-token'))
  const [authUser, setAuthUser] = useState<{name?: string; email?: string} | null>(() => JSON.parse(localStorage.getItem('personal-os-user') || 'null'))
  const logout = () => { localStorage.removeItem('personal-os-token'); localStorage.removeItem('personal-os-user'); localStorage.removeItem('personal-os-profile'); setAuthToken(null) }
  const [active, setActive] = useState('Dashboard')
  const [open, setOpen] = useState(false)
  const [completed, setCompleted] = useState<string[]>([])
  const isDashboard = active === 'Dashboard'
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const token = params.get('oauth_token')
    if (!token) return
    localStorage.setItem('personal-os-token', token)
    fetch(`${API}/auth/me`, { headers: { Authorization: `Bearer ${token}` } })
      .then((response) => response.json())
      .then((user) => { localStorage.setItem('personal-os-user', JSON.stringify(user)); setAuthToken(token); setAuthUser(user); window.history.replaceState({}, '', window.location.pathname) })
      .catch(() => { localStorage.removeItem('personal-os-token') })
  }, [])
  useEffect(() => { const key = authUser?.email ? `personal-os-theme-${authUser.email.toLowerCase()}` : 'personal-os-theme'; const saved = authUser?.email ? (localStorage.getItem(key) || 'light') : 'light'; localStorage.setItem('personal-os-theme', saved); document.documentElement.classList.toggle('dark', saved === 'dark'); let applied = saved; const timer = setInterval(() => { const current = authUser?.email ? (localStorage.getItem('personal-os-theme') || 'light') : 'light'; if (current !== applied) { applied = current; localStorage.setItem(key, current) } document.documentElement.classList.toggle('dark', current === 'dark') }, 150); return () => clearInterval(timer) }, [authUser?.email])
  useEffect(() => { if (authUser) localStorage.setItem('personal-os-profile', JSON.stringify({name: authUser.name || '', email: authUser.email || '', timezone: 'Asia/Calcutta'})) }, [authUser])
  useEffect(() => { const navigate = (event: Event) => { const target = (event as CustomEvent<string>).detail; if (target) setActive(target) }; window.addEventListener('personal-os:navigate', navigate); return () => window.removeEventListener('personal-os:navigate', navigate) }, [])
  useEffect(() => { if (active === 'Settings') setOpen(false) }, [active])
  useEffect(() => { const name = authUser?.name || ''; const initials = name.split(/\s+/).filter(Boolean).map(part => part[0]).join('').slice(0, 2).toUpperCase() || 'U'; const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let node: Node | null; while (node = walker.nextNode()) { if (node.nodeValue?.trim() === 'SN') node.nodeValue = initials } }, [authUser])
  const handleAuth = (token: string) => { setAuthToken(token); setAuthUser(JSON.parse(localStorage.getItem('personal-os-user') || 'null')) }
  if (!authToken) return <AuthPage onAuth={handleAuth} />

  const content = isDashboard ? <LiveDashboard navigate={setActive} userName={authUser?.name} /> : active === 'Tasks' ? <TasksPage /> : active === 'Calendar' ? <CalendarPage /> : active === 'Notes' ? <RichNotesPage /> : active === 'Knowledge Base' ? <KnowledgePage /> : active === 'Documents' ? <DocumentsPage /> : active === 'Publications' ? <PublicationsPage /> : active === 'Finance' ? <FinancePage /> : active === 'AI Assistant' ? <AIAssistantPage /> : active === 'Projects' ? <><GitHubMirror/><ProjectsPage/></> : active === 'Habits' ? <HabitsPage /> : active === 'Analytics' ? <AnalyticsPage /> : active === 'Settings' ? <div><SettingsPage/><GitHubSettings/><div className="mx-auto mt-5 max-w-4xl px-5 sm:px-9"><button onClick={logout} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-600 hover:bg-red-50">Log out</button></div></div> : <ModulePlaceholder title={active} />

  return <div className="min-h-screen bg-mist lg:flex">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-black/5 bg-white p-5 transition-transform lg:static lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-8 flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-forest text-lg font-black text-white">P</div><div><p className="font-bold tracking-tight">Personal OS</p><p className="text-xs text-muted">Your life, in flow</p></div></div><button className="lg:hidden" onClick={() => setOpen(false)}><X size={20}/></button></div>
      <nav className="flex-1 space-y-1 overflow-y-auto">{nav.map(([name, Icon]) => <button key={name} onClick={() => {setActive(name); setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active === name ? 'bg-forest text-white shadow-sm' : 'text-slate-600 hover:bg-slate-100'}`}><Icon size={17}/>{name}</button>)}</nav>
      <div className="mt-4 border-t border-slate-100 pt-4"><button onClick={() => setActive('Settings')} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-100"><Settings size={17}/>Settings</button><button className="mt-2 flex w-full items-center gap-3 rounded-xl bg-lime px-3 py-2.5 text-sm font-semibold text-ink"><Sparkles size={17}/>Plugin Marketplace</button></div>
    </aside>
    {open && <button aria-label="Close menu" onClick={() => setOpen(false)} className="fixed inset-0 z-20 bg-black/20 lg:hidden" />}
    <main className="min-w-0 flex-1"><header className="flex items-center justify-between px-5 py-5 sm:px-9"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setOpen(true)}><Menu/></button><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 text-muted" size={17}/><input aria-label="Search" placeholder="Search your space..." className="w-72 rounded-xl border border-slate-200 bg-white py-2 pl-10 pr-4 text-sm outline-none ring-forest focus:ring-2"/></div></div><div className="flex items-center gap-3"><button onClick={() => setActive('AI Assistant')} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-muted shadow-sm"><Bot size={19}/></button><div className="grid h-10 w-10 place-items-center rounded-full bg-[#d8e9d0] font-semibold text-forest">SN</div></div></header>{content}{isDashboard && <button onClick={() => setActive('AI Assistant')} className="fixed bottom-6 right-6 z-10 inline-flex items-center gap-2 rounded-full bg-ink px-4 py-3 text-sm font-semibold text-white shadow-xl"><Bot size={17}/>Ask AI</button>}</main>
  </div>
}

function LiveDashboard({navigate, userName}: {navigate: (page: string) => void; userName?: string}) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState('')
  const load = async () => { try { const response = await fetch('http://127.0.0.1:8000/api/v1/dashboard'); if (!response.ok) throw Error(); setData(await response.json()); setError('') } catch { setError('Start FastAPI to load live dashboard data.') } }
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer) }, [])
  useEffect(() => { const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); let node: Node | null; while (node = walker.nextNode()) { if (node.nodeValue?.includes('Good morning, Saran.')) node.nodeValue = node.nodeValue.replace('Good morning, Saran.', `Welcome, ${userName || 'there'}.`) } }, [userName])
  const items = data?.tasks?.items || []
  return <div className="mx-auto max-w-7xl px-5 pb-12 sm:px-9"><section className="mb-8 flex items-end justify-between"><div><p className="mb-2 text-sm font-medium text-forest">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Good morning, Saran.</h1><p className="mt-2 text-muted">Your live personal OS overview.</p></div><button onClick={load} className="rounded-xl bg-forest px-4 py-2.5 text-sm font-semibold text-white">Refresh</button></section><section className="grid gap-4 md:grid-cols-4"><Stat label="Open tasks" value={data ? String(data.tasks.open) : '—'} detail={`${data?.tasks.completed || 0} completed`} icon={<CheckCircle2/>} tone="bg-[#e8f5ed] text-forest"/><Stat label="Spent this month" value={data ? `₹${Number(data.finance.month_total).toLocaleString('en-IN',{maximumFractionDigits:0})}` : '—'} detail="Finance tracker" icon={<WalletCards/>} tone="bg-[#fff3d9] text-[#a86600]"/><Stat label="Upcoming events" value={data ? String(data.calendar.upcoming) : '—'} detail="From your calendar" icon={<CalendarDays/>} tone="bg-[#ececff] text-[#5553a8]"/><Stat label="Publications" value={data ? String(data.publications) : '—'} detail="Your research profile" icon={<BookOpen/>} tone="bg-[#e4f3fb] text-[#176a98]"/></section><section className="mt-7 grid gap-6 lg:grid-cols-[1.3fr_1fr]"><div className="rounded-2xl bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Open tasks</h2><p className="mt-1 text-sm text-muted">Live from your task list.</p></div><button onClick={load} className="text-xs font-semibold text-forest">Refresh</button></div>{items.length?<div className="space-y-2">{items.map((item:any)=><div key={item.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="h-2 w-2 rounded-full bg-forest"/><span className="min-w-0 flex-1 text-sm font-medium">{item.title}</span><span className="text-xs text-muted">{item.due_date ? new Date(`${item.due_date}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}) : 'No due date'}</span></div>)}</div>:<div className="py-10 text-center text-sm text-muted">No open tasks. You’re clear.</div>}</div><div className="rounded-2xl bg-ink p-6 text-white"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-lime"><TrendingUp size={19}/></span><h2 className="mt-7 text-xl font-bold">Your system is connected.</h2><p className="mt-2 text-sm leading-6 text-white/60">Dashboard metrics update from Tasks, Finance, Calendar, and Publications automatically.</p></div></section>{error&&<p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</p>}</div>
}

function Dashboard({ completed, toggle }: { completed: string[], toggle: (title: string) => void }) {
  const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'
  return <div className="mx-auto max-w-7xl px-5 pb-12 sm:px-9"><section className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-medium text-forest">Thursday, July 16</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{greeting}, Saran.</h1><p className="mt-2 text-muted">A clear day starts with one meaningful thing.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-forest px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={17}/>Create new</button></section>
    <section className="grid gap-4 md:grid-cols-3"><Stat label="Tasks due today" value={`${tasks.length - completed.length}`} detail="Stay focused" icon={<CheckCircle2/>} tone="bg-[#e8f5ed] text-forest"/><Stat label="Habit streak" value="7 days" detail="Best: 12 days" icon={<HeartPulse/>} tone="bg-[#fff3d9] text-[#a86600]"/><Stat label="Weekly focus" value="68%" detail="Up 12% this week" icon={<TrendingUp/>} tone="bg-[#ececff] text-[#5553a8]"/></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Today’s focus</h2><p className="mt-1 text-sm text-muted">Small actions, real momentum.</p></div><button className="text-muted"><MoreHorizontal/></button></div><div className="space-y-2">{tasks.map(task => <button key={task.title} onClick={() => toggle(task.title)} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-slate-50"><span className={`grid h-5 w-5 place-items-center rounded-full border ${completed.includes(task.title) ? 'border-forest bg-forest text-white' : 'border-slate-300'}`}>{completed.includes(task.title) && <CheckCircle2 size={14}/>}</span><span className="min-w-0 flex-1"><span className={`block text-sm font-medium ${completed.includes(task.title) ? 'text-muted line-through' : ''}`}>{task.title}</span><span className="text-xs text-muted">{task.project}</span></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-muted">{task.due}</span></button>)}</div><button className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-forest">View all tasks <ChevronRight size={16}/></button></div>
      <div className="rounded-2xl bg-ink p-6 text-white"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-lime"><Sparkles size={19}/></span><span className="rounded-full bg-white/10 px-3 py-1 text-xs">AI Assistant</span></div><h2 className="mt-7 text-xl font-bold">What can I help you move forward today?</h2><p className="mt-2 text-sm leading-6 text-white/60">Plan a project, find a note, summarize documents, or turn thoughts into tasks.</p><button className="mt-6 w-full rounded-xl bg-lime px-4 py-2.5 text-sm font-bold text-ink">Ask Personal OS</button></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Quick capture</h2><Plus size={18} className="text-forest"/></div><textarea placeholder="What’s on your mind?" className="mt-4 h-20 w-full resize-none rounded-xl bg-slate-50 p-3 text-sm outline-none focus:ring-2 focus:ring-forest/30"/><div className="mt-3 flex gap-2"><button className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-medium">Note</button><button className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-medium">Task</button><button className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-medium">Bookmark</button></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Recent spaces</h2><p className="mt-1 text-sm text-muted">Pick up where you left off</p></div><ChevronRight className="text-muted"/></div><div className="mt-4 grid grid-cols-3 gap-3"><Space icon={<FolderKanban/>} label="Personal OS" color="bg-[#e8f5ed] text-forest"/><Space icon={<BookOpen/>} label="Reading notes" color="bg-[#fff2dc] text-[#a86600]"/><Space icon={<WalletCards/>} label="Finances" color="bg-[#ececff] text-[#5553a8]"/></div></div></section>
  </div>
}

function Stat({label,value,detail,icon,tone}:{label:string,value:string,detail:string,icon:React.ReactNode,tone:string}) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted">{detail}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}>{icon}</span></div></div> }
function Space({icon,label,color}:{icon:React.ReactNode,label:string,color:string}) { return <button className="rounded-xl bg-slate-50 p-3 text-left hover:bg-slate-100"><span className={`grid h-8 w-8 place-items-center rounded-lg ${color}`}>{icon}</span><span className="mt-3 block truncate text-xs font-medium">{label}</span></button> }
function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([]); const [selected, setSelected] = useState<Note | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const editor = useRef<HTMLTextAreaElement>(null)
  const load = async () => { try { const res = await fetch(`${API}/notes`); if (!res.ok) throw new Error(); const loaded: Note[] = await res.json(); setNotes(loaded); setSelected(current => current ? loaded.find(note => note.id === current.id) || loaded[0] || null : loaded[0] || null); setError('') } catch { setError('Start the FastAPI server to save pages.') } }
  useEffect(() => { load() }, [])
  const create = async () => { try { const res = await fetch(`${API}/notes`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({title:'Untitled', icon:'📝'})}); if (!res.ok) throw new Error(); const note: Note = await res.json(); setNotes(current => [note, ...current]); setSelected(note); setError('') } catch { setError('Could not create a page. Is the API running?') } }
  const updateLocal = (changes: Partial<Note>) => { if (!selected) return; const next = {...selected, ...changes}; setSelected(next); setNotes(current => current.map(note => note.id === next.id ? next : note)) }
  const save = async () => { if (!selected) return; setSaving(true); try { const res = await fetch(`${API}/notes/${selected.id}`, {method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({title:selected.title || 'Untitled', content:selected.content, icon:selected.icon})}); if (!res.ok) throw new Error(); const saved: Note = await res.json(); setSelected(saved); setNotes(current => current.map(note => note.id === saved.id ? saved : note)); setError('') } catch { setError('Could not save this page.') } finally { setSaving(false) } }
  const remove = async () => { if (!selected || !confirm(`Delete “${selected.title}”?`)) return; const removed = selected; setNotes(current => current.filter(note => note.id !== removed.id)); setSelected(notes.find(note => note.id !== removed.id) || null); try { const res = await fetch(`${API}/notes/${removed.id}`, {method:'DELETE'}); if (!res.ok) throw new Error() } catch { setNotes(current => [removed, ...current]); setSelected(removed); setError('Could not delete this page.') } }
  const insert = (text: string) => { const field = editor.current; if (!selected || !field) return; const start = field.selectionStart, end = field.selectionEnd; updateLocal({content: `${selected.content.slice(0,start)}${text}${selected.content.slice(end)}`}); requestAnimationFrame(() => { field.focus(); field.setSelectionRange(start + text.length, start + text.length) }) }
  return <div className="mx-auto max-w-7xl px-5 pb-12 sm:px-9"><section className="mb-6 flex items-end justify-between"><div><p className="mb-2 text-sm font-medium text-forest">NOTES</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Your thinking space.</h1><p className="mt-2 text-muted">Build a personal wiki, one page at a time.</p></div><button onClick={create} className="inline-flex items-center gap-2 rounded-xl bg-forest px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/>New page</button></section>
    <section className="grid min-h-[620px] overflow-hidden rounded-2xl bg-white shadow-sm lg:grid-cols-[245px_1fr]"><aside className="border-b border-slate-100 bg-[#fafbf9] p-4 lg:border-b-0 lg:border-r"><div className="mb-4 flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-bold"><PanelLeft size={16}/>Pages</span><button onClick={create} className="text-forest"><Plus size={17}/></button></div><div className="space-y-1">{notes.map(note => <button key={note.id} onClick={() => setSelected(note)} className={`flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm ${selected?.id === note.id ? 'bg-[#e8f5ed] font-semibold text-forest' : 'text-slate-600 hover:bg-slate-100'}`}><span>{note.icon}</span><span className="truncate">{note.title || 'Untitled'}</span></button>)}{!notes.length && <p className="px-2 py-5 text-xs leading-5 text-muted">Create your first page to begin building your knowledge space.</p>}</div></aside>
      <div className="flex min-w-0 flex-col">{selected ? <><div className="flex items-center justify-between border-b border-slate-100 px-5 py-3"><div className="flex gap-1"><ToolButton label="Heading" icon={<Type size={16}/>} onClick={() => insert('\n## ')}/><ToolButton label="Bold" icon={<Bold size={16}/>} onClick={() => insert('**bold text**')}/><ToolButton label="Bulleted list" icon={<List size={16}/>} onClick={() => insert('\n- ')}/><ToolButton label="Quote" icon={<Quote size={16}/>} onClick={() => insert('\n> ')}/></div><div className="flex items-center gap-2"><span className="hidden text-xs text-muted sm:block">{saving ? 'Saving…' : 'Changes not saved'}</span><button onClick={save} className="inline-flex items-center gap-1.5 rounded-lg bg-forest px-3 py-1.5 text-xs font-semibold text-white"><Save size={14}/>Save</button><button onClick={remove} className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-red-50 hover:text-red-600" aria-label="Delete page"><Trash2 size={16}/></button></div></div><div className="mx-auto flex w-full max-w-3xl flex-1 flex-col px-6 py-10 sm:px-12"><div className="mb-6 flex items-center gap-3"><input value={selected.icon} onChange={event => updateLocal({icon:event.target.value.slice(0,2)})} className="w-10 bg-transparent text-3xl outline-none" aria-label="Page icon"/><input value={selected.title} onChange={event => updateLocal({title:event.target.value})} placeholder="Untitled" className="min-w-0 flex-1 bg-transparent text-3xl font-bold tracking-tight outline-none placeholder:text-slate-300"/></div><textarea ref={editor} value={selected.content} onChange={event => updateLocal({content:event.target.value})} placeholder="Start writing, or use the toolbar to add blocks…" className="min-h-[380px] w-full resize-none border-0 bg-transparent text-[15px] leading-8 outline-none placeholder:text-slate-400"/><p className="mt-4 text-xs text-muted">Simple Markdown supported: ## Heading, **bold**, - lists, and &gt; quotes.</p></div></> : <div className="grid flex-1 place-items-center p-8 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f5ed] text-forest"><FileText/></span><p className="mt-4 font-semibold">Select or create a page</p><p className="mt-1 text-sm text-muted">Your notes will live here.</p></div></div>}</div></section>{error && <p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</p>}</div>
}
function ToolButton({label, icon, onClick}:{label:string, icon:React.ReactNode, onClick:()=>void}) { return <button onClick={onClick} aria-label={label} title={label} className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-slate-100 hover:text-ink">{icon}</button> }
function CalendarPage() {
  const today = new Date()
  const [cursor, setCursor] = useState(new Date(today.getFullYear(), today.getMonth(), 1))
  const [events, setEvents] = useState<CalendarEvent[]>([])
  const [title, setTitle] = useState('')
  const [date, setDate] = useState(today.toISOString().slice(0, 10))
  const [time, setTime] = useState('09:00')
  const [color, setColor] = useState<CalendarEvent['color']>('forest')
  const [error, setError] = useState('')
  const monthKey = `${cursor.getFullYear()}-${String(cursor.getMonth() + 1).padStart(2, '0')}`
  const load = async () => { try { const res = await fetch(`${API}/calendar/events?month=${monthKey}`); if (!res.ok) throw new Error(); setEvents(await res.json()); setError('') } catch { setError('Start the FastAPI server to save calendar events.') } }
  useEffect(() => { load() }, [monthKey])
  const add = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; try { const res = await fetch(`${API}/calendar/events`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({title, event_date:date, start_time:time || null, color})}); if (!res.ok) throw new Error(); const created: CalendarEvent = await res.json(); if (created.event_date.startsWith(monthKey)) setEvents(current => [...current, created]); setTitle(''); setError('') } catch { setError('Could not save this event. Is the API running?') } }
  const remove = async (id: number) => { const existing = events; setEvents(current => current.filter(event => event.id !== id)); try { const res = await fetch(`${API}/calendar/events/${id}`, {method:'DELETE'}); if (!res.ok) throw new Error() } catch { setEvents(existing); setError('Could not delete this event.') } }
  const firstDay = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const leading = (firstDay.getDay() + 6) % 7; const days = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate()
  const cells = Array.from({length: Math.ceil((leading + days) / 7) * 7}, (_, index) => index - leading + 1)
  const label = cursor.toLocaleDateString(undefined, {month:'long', year:'numeric'})
  const colors = {forest:'bg-forest/10 text-forest', purple:'bg-[#ececff] text-[#5553a8]', orange:'bg-[#fff3d9] text-[#a86600]', blue:'bg-[#e4f3fb] text-[#176a98]'}
  return <div className="mx-auto max-w-7xl px-5 pb-12 sm:px-9"><section className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-medium text-forest">CALENDAR</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Make room for what matters.</h1><p className="mt-2 text-muted">Plan your time with enough space to breathe.</p></div><div className="flex items-center gap-2"><button onClick={() => setCursor(new Date(today.getFullYear(), today.getMonth(), 1))} className="rounded-xl bg-white px-3 py-2 text-sm font-medium shadow-sm">Today</button><button onClick={() => setCursor(current => new Date(current.getFullYear(), current.getMonth() - 1, 1))} className="grid h-10 w-10 place-items-center rounded-xl bg-white shadow-sm"><ChevronLeft size={18}/></button><button onClick={() => setCursor(current => new Date(current.getFullYear(), current.getMonth() + 1, 1))} className="grid h-10 w-10 place-items-center rounded-xl bg-white shadow-sm"><ChevronRight size={18}/></button></div></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_300px]"><div className="overflow-hidden rounded-2xl bg-white shadow-sm"><h2 className="px-5 pb-4 pt-5 text-lg font-bold sm:px-6">{label}</h2><div className="grid grid-cols-7 border-y border-slate-100">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day => <div key={day} className="px-2 py-3 text-center text-xs font-semibold text-muted">{day}</div>)}</div><div className="grid grid-cols-7">{cells.map((day, index) => { const isCurrent = day > 0 && day <= days; const iso = isCurrent ? `${monthKey}-${String(day).padStart(2, '0')}` : ''; const eventList = events.filter(event => event.event_date === iso); const isToday = iso === today.toISOString().slice(0,10); return <div key={index} className={`min-h-28 border-b border-r border-slate-100 p-2 sm:min-h-32 ${isCurrent ? '' : 'bg-slate-50/60'}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-xs ${isToday ? 'bg-forest font-bold text-white' : 'text-muted'}`}>{isCurrent ? day : ''}</span><div className="mt-1 space-y-1">{eventList.slice(0, 3).map(event => <div key={event.id} className={`group truncate rounded-md px-1.5 py-1 text-[10px] font-semibold sm:text-xs ${colors[event.color]}`} title={event.title}>{event.start_time && <span className="mr-1 opacity-70">{event.start_time}</span>}{event.title}</div>)}</div></div> })}</div></div>
      <aside className="h-fit rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8f5ed] text-forest"><CalendarDays size={18}/></span><h2 className="font-bold">New event</h2></div><form onSubmit={add} className="mt-5 space-y-3"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Event title" className="w-full rounded-xl bg-slate-50 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-forest/30"/><input type="date" value={date} onChange={event => setDate(event.target.value)} className="w-full rounded-xl bg-slate-50 px-3 py-2.5 text-sm outline-none"/><input type="time" value={time} onChange={event => setTime(event.target.value)} className="w-full rounded-xl bg-slate-50 px-3 py-2.5 text-sm outline-none"/><div className="flex gap-2">{(['forest','purple','orange','blue'] as const).map(choice => <button type="button" onClick={() => setColor(choice)} key={choice} aria-label={`${choice} color`} className={`h-7 w-7 rounded-full ${choice === 'forest' ? 'bg-forest' : choice === 'purple' ? 'bg-[#7371c8]' : choice === 'orange' ? 'bg-[#d89529]' : 'bg-[#4a9dca]'} ${color === choice ? 'ring-2 ring-offset-2 ring-ink' : ''}`}/>)}</div><button className="w-full rounded-xl bg-forest py-2.5 text-sm font-semibold text-white">Add event</button></form>{error && <p className="mt-4 rounded-xl bg-amber-50 px-3 py-2 text-xs text-amber-800">{error}</p>}<div className="mt-7 border-t border-slate-100 pt-5"><p className="text-sm font-bold">This month</p><div className="mt-3 space-y-2">{events.length ? events.map(event => <div key={event.id} className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${event.color === 'forest' ? 'bg-forest' : event.color === 'purple' ? 'bg-[#7371c8]' : event.color === 'orange' ? 'bg-[#d89529]' : 'bg-[#4a9dca]'}`}/><span className="min-w-0 flex-1 truncate text-xs">{event.title}</span><button onClick={() => remove(event.id)} className="text-muted hover:text-red-600" aria-label={`Delete ${event.title}`}><Trash2 size={14}/></button></div>) : <p className="text-xs leading-5 text-muted">No events this month yet.</p>}</div></div></aside></section>
  </div>
}
function TasksPage() {
  const [items, setItems] = useState<PersonalTask[]>([])
  const [title, setTitle] = useState('')
  const [project, setProject] = useState('Personal OS')
  const [priority, setPriority] = useState<PersonalTask['priority']>('medium')
  const [dueDate, setDueDate] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const load = async () => {
    try { const response = await fetch(`${API}/tasks`); if (!response.ok) throw new Error(); setItems(await response.json()); setError('') }
    catch { setError('Start the FastAPI server to save tasks.'); }
    finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!title.trim()) return
    try {
      const response = await fetch(`${API}/tasks`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({title, project: project || null, priority, due_date: dueDate || null}) })
      if (!response.ok) throw new Error(); const created: PersonalTask = await response.json(); setItems(current => [created, ...current]); setTitle(''); setDueDate(''); setError('')
    } catch { setError('Could not save the task. Is the API running?') }
  }
  const toggle = async (item: PersonalTask) => {
    const next = {...item, completed: !item.completed}; setItems(current => current.map(task => task.id === item.id ? next : task))
    try { const response = await fetch(`${API}/tasks/${item.id}`, {method: 'PATCH', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({completed: next.completed})}); if (!response.ok) throw new Error() }
    catch { setItems(current => current.map(task => task.id === item.id ? item : task)); setError('Could not update this task.') }
  }
  const open = items.filter(item => !item.completed), done = items.filter(item => item.completed)
  return <div className="mx-auto max-w-5xl px-5 pb-12 sm:px-9"><section className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-medium text-forest">TASKS</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Make progress, calmly.</h1><p className="mt-2 text-muted">{open.length} open task{open.length === 1 ? '' : 's'} waiting for your attention.</p></div><div className="rounded-xl bg-white px-4 py-2 text-sm text-muted shadow-sm"><span className="font-bold text-ink">{done.length}</span> completed</div></section>
    <form onSubmit={submit} className="rounded-2xl bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_140px_120px_145px_auto]"><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Add a task..." className="min-w-0 rounded-xl bg-slate-50 px-4 py-3 text-sm outline-none ring-forest focus:ring-2"/><input value={project} onChange={event => setProject(event.target.value)} placeholder="Project" className="rounded-xl bg-slate-50 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-forest/30"/><select value={priority} onChange={event => setPriority(event.target.value as PersonalTask['priority'])} className="rounded-xl bg-slate-50 px-3 py-3 text-sm outline-none"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} className="rounded-xl bg-slate-50 px-3 py-3 text-sm outline-none"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-forest px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>Add</button></div></form>
    {error && <p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{error}</p>}
    <section className="mt-7 rounded-2xl bg-white p-5 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Open tasks</h2><span className="rounded-full bg-[#e8f5ed] px-2.5 py-1 text-xs font-semibold text-forest">{open.length}</span></div>{loading ? <p className="py-8 text-center text-sm text-muted">Loading your tasks…</p> : open.length ? <div className="space-y-2">{open.map(item => <TaskRow key={item.id} item={item} toggle={toggle}/>)}</div> : <EmptyTasks/>}</section>
    {done.length > 0 && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="mb-4 font-bold text-muted">Completed</h2><div className="space-y-2">{done.map(item => <TaskRow key={item.id} item={item} toggle={toggle}/>)}</div></section>}
  </div>
}
function TaskRow({item, toggle}:{item:PersonalTask, toggle:(item:PersonalTask)=>void}) { const colors = {low:'bg-slate-100 text-slate-600', medium:'bg-[#fff3d9] text-[#9a6500]', high:'bg-[#fde8e7] text-[#b13a31]'}; return <div className="flex items-center gap-3 rounded-xl p-3 hover:bg-slate-50"><button onClick={() => toggle(item)} aria-label={`Mark ${item.title} ${item.completed ? 'incomplete' : 'complete'}`} className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border ${item.completed ? 'border-forest bg-forest text-white' : 'border-slate-300'}`}>{item.completed && <CheckCircle2 size={14}/>}</button><div className="min-w-0 flex-1"><p className={`text-sm font-medium ${item.completed ? 'text-muted line-through' : ''}`}>{item.title}</p><p className="mt-0.5 text-xs text-muted">{item.project || 'No project'}{item.due_date ? ` · Due ${new Date(`${item.due_date}T00:00:00`).toLocaleDateString(undefined, {month:'short', day:'numeric'})}` : ''}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${colors[item.priority]}`}>{item.priority}</span></div> }
function EmptyTasks() { return <div className="py-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f5ed] text-forest"><CheckCircle2/></span><p className="mt-3 font-semibold">Your list is clear</p><p className="mt-1 text-sm text-muted">Add a task above when something needs your attention.</p></div> }
function ModulePlaceholder({title}:{title:string}) { return <div className="mx-auto max-w-7xl px-5 pt-12 sm:px-9"><div className="max-w-xl rounded-3xl bg-white p-8 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e8f5ed] text-forest"><Sparkles/></span><h1 className="mt-6 text-3xl font-bold">{title}</h1><p className="mt-3 leading-7 text-muted">This module is ready for its first workflow. The navigation and API foundation are in place, so it can be developed independently without changing the rest of your Personal OS.</p><button className="mt-6 rounded-xl bg-forest px-4 py-2.5 text-sm font-semibold text-white">Set up {title}</button></div></div> }

export default App
