import { useEffect, useRef, useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react'

const parse = (value: string) => { const [year, month, day] = value.split('-').map(Number); return year && month && day ? new Date(year, month - 1, day) : new Date() }
const format = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`

export default function DatePicker({ value, onChange, min }: { value: string; onChange: (value: string) => void; min?: string }) {
  const [open, setOpen] = useState(false)
  const [month, setMonth] = useState(() => { const date = parse(value); return new Date(date.getFullYear(), date.getMonth(), 1) })
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate()
  const leading = (new Date(month.getFullYear(), month.getMonth(), 1).getDay() + 6) % 7
  const cells = Array.from({ length: Math.ceil((leading + days) / 7) * 7 }, (_, index) => index - leading + 1)
  const selected = value || ''
  return <div ref={ref} className="relative"><button type="button" onClick={() => setOpen(!open)} className="flex w-full items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-left text-sm"><span>{value || 'Select date'}</span><CalendarDays size={17} className="text-muted" /></button>{open && <div className="absolute left-0 top-full z-40 mt-2 w-[min(19rem,calc(100vw-2.5rem))] rounded-2xl border border-slate-200 bg-white p-4 shadow-xl"><div className="mb-3 flex items-center justify-between"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-slate-100"><ChevronLeft size={16}/></button><p className="text-sm font-bold">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</p><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-slate-100"><ChevronRight size={16}/></button></div><div className="grid grid-cols-7 gap-1 text-center text-[11px] font-semibold text-muted">{['Mo','Tu','We','Th','Fr','Sa','Su'].map(day => <span key={day} className="py-1">{day}</span>)}{cells.map((day, index) => { const date = day > 0 && day <= days ? new Date(month.getFullYear(), month.getMonth(), day) : null; const dateValue = date ? format(date) : ''; const past = Boolean(min && dateValue < min); return <button type="button" key={index} disabled={!date || past} onClick={() => { if (date && !past) { onChange(dateValue); setOpen(false) } }} className={`h-9 rounded-lg text-sm ${!date ? 'invisible' : past ? 'cursor-not-allowed text-slate-300' : dateValue === selected ? 'bg-forest font-bold text-white' : 'hover:bg-[#e8f5ed]'}`}>{date ? day : ''}</button>})}</div><button type="button" onClick={() => { const now = new Date(); const dateValue = format(now); if (!min || dateValue >= min) { onChange(dateValue); setMonth(new Date(now.getFullYear(), now.getMonth(), 1)); setOpen(false) } }} className="mt-3 w-full rounded-lg bg-slate-50 py-2 text-xs font-semibold text-forest">Today</button></div>}</div>
}
